/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 4 "./example_extern.c"
void __globinit_example_extern(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 431
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
#line 1 "./example_extern.h"
int readCrest(void) ;
#line 2
int sum(int a , int b , int c ) ;
#line 4 "./example_extern.h"
int readCrest(void) 
{ 
  int fc ;

  {
  __CrestCall(1, 1);

#line 6
  scanf((char const   * __restrict  )"%d", & fc);
  __CrestClearStack(2);
  {
  __CrestLoad(3, (unsigned long )(& fc), (long long )fc);
  __CrestReturn(4);
#line 7
  return (fc);
  }
}
}
#line 10 "./example_extern.h"
int sum(int a , int b , int c ) 
{ 
  int __retres4 ;

  {
  __CrestCall(8, 2);
  __CrestStore(7, (unsigned long )(& c));
  __CrestStore(6, (unsigned long )(& b));
  __CrestStore(5, (unsigned long )(& a));
  __CrestLoad(13, (unsigned long )(& a), (long long )a);
  __CrestLoad(12, (unsigned long )(& b), (long long )b);
  __CrestApply2(11, 0, (long long )(a + b));
  __CrestLoad(10, (unsigned long )(& c), (long long )c);
  __CrestApply2(9, 0, (long long )((a + b) + c));
  __CrestStore(14, (unsigned long )(& __retres4));
#line 11
  __retres4 = (a + b) + c;
  {
  __CrestLoad(15, (unsigned long )(& __retres4), (long long )__retres4);
  __CrestReturn(16);
#line 10
  return (__retres4);
  }
}
}
#line 4 "./example_extern.c"
int main(void) 
{ 
  int a ;
  int b ;
  int c ;
  int s ;
  int __retres5 ;

  {
  __globinit_example_extern();
  __CrestCall(17, 3);
#line 8
  scanf((char const   * __restrict  )"%d", & a);
  __CrestClearStack(18);
#line 9
  scanf((char const   * __restrict  )"%d", & b);
  __CrestClearStack(19);
#line 11
  c = readCrest();
  __CrestHandleReturn(21, (long long )c);
  __CrestStore(20, (unsigned long )(& c));
  __CrestLoad(22, (unsigned long )(& a), (long long )a);
  __CrestLoad(23, (unsigned long )(& b), (long long )b);
  __CrestLoad(24, (unsigned long )(& c), (long long )c);
#line 13
  s = sum(a, b, c);
  __CrestHandleReturn(26, (long long )s);
  __CrestStore(25, (unsigned long )(& s));
  __CrestLoad(27, (unsigned long )(& s), (long long )s);
#line 14
  printf((char const   * __restrict  )"%d", s);
  __CrestClearStack(28);
  __CrestLoad(29, (unsigned long )0, (long long )0);
  __CrestStore(30, (unsigned long )(& __retres5));
#line 17
  __retres5 = 0;
  __CrestLoad(31, (unsigned long )(& __retres5), (long long )__retres5);
  __CrestReturn(32);
#line 4
  return (__retres5);
}
}
void __globinit_example_extern(void) 
{ 


  {
  __CrestInit();
}
}
