/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 4 "./example_Array.c"
void __globinit_example_Array(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 202 "/home/hyorm1226/Development/crest-0.1.2/bin/../include/crest.h"
extern void __CrestInt(int *x )  __attribute__((__crest_skip__)) ;
#line 4 "./example_Array.c"
int main(void) 
{ 
  int num ;
  int arr_2d[10][10] ;
  int i ;
  int j ;
  int i___0 ;
  int j___0 ;
  int __retres7 ;

  {
  __globinit_example_Array();
  __CrestCall(1, 1);
  __CrestLoad(2, (unsigned long )0, (long long )10);
  __CrestStore(3, (unsigned long )(& num));
#line 6
  num = 10;
  __CrestLoad(4, (unsigned long )0, (long long )0);
  __CrestStore(5, (unsigned long )(& i));
#line 9
  i = 0;
#line 9
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(8, (unsigned long )(& i), (long long )i);
    __CrestLoad(7, (unsigned long )(& num), (long long )num);
    __CrestApply2(6, 16, (long long )(i < num));
#line 9
    if (i < num) {
      __CrestBranch(9, 6, 1);

    } else {
      __CrestBranch(10, 7, 0);
#line 9
      goto while_break;
    }
    }
    __CrestLoad(11, (unsigned long )0, (long long )0);
    __CrestStore(12, (unsigned long )(& j));
#line 10
    j = 0;
    {
#line 10
    while (1) {
      while_continue___0: /* CIL Label */ ;
      {
      __CrestLoad(15, (unsigned long )(& j), (long long )j);
      __CrestLoad(14, (unsigned long )(& num), (long long )num);
      __CrestApply2(13, 16, (long long )(j < num));
#line 10
      if (j < num) {
        __CrestBranch(16, 13, 1);

      } else {
        __CrestBranch(17, 14, 0);
#line 10
        goto while_break___0;
      }
      }
#line 11
      __CrestInt(& arr_2d[i][j]);
      __CrestLoad(20, (unsigned long )(& j), (long long )j);
      __CrestLoad(19, (unsigned long )0, (long long )1);
      __CrestApply2(18, 0, (long long )(j + 1));
      __CrestStore(21, (unsigned long )(& j));
#line 10
      j ++;
    }
    while_break___0: /* CIL Label */ ;
    }
    __CrestLoad(24, (unsigned long )(& i), (long long )i);
    __CrestLoad(23, (unsigned long )0, (long long )1);
    __CrestApply2(22, 0, (long long )(i + 1));
    __CrestStore(25, (unsigned long )(& i));
#line 9
    i ++;
  }
  while_break: /* CIL Label */ 
  __CrestLoad(26, (unsigned long )0, (long long )0);
  __CrestStore(27, (unsigned long )(& i___0));
#line 14
  i___0 = 0;
#line 14
  while (1) {
    while_continue___1: /* CIL Label */ ;
    {
    __CrestLoad(30, (unsigned long )(& i___0), (long long )i___0);
    __CrestLoad(29, (unsigned long )(& num), (long long )num);
    __CrestApply2(28, 16, (long long )(i___0 < num));
#line 14
    if (i___0 < num) {
      __CrestBranch(31, 24, 1);

    } else {
      __CrestBranch(32, 25, 0);
#line 14
      goto while_break___1;
    }
    }
    __CrestLoad(33, (unsigned long )0, (long long )0);
    __CrestStore(34, (unsigned long )(& j___0));
#line 15
    j___0 = 0;
    {
#line 15
    while (1) {
      while_continue___2: /* CIL Label */ ;
      {
      __CrestLoad(37, (unsigned long )(& j___0), (long long )j___0);
      __CrestLoad(36, (unsigned long )(& num), (long long )num);
      __CrestApply2(35, 16, (long long )(j___0 < num));
#line 15
      if (j___0 < num) {
        __CrestBranch(38, 31, 1);

      } else {
        __CrestBranch(39, 32, 0);
#line 15
        goto while_break___2;
      }
      }
      __CrestLoad(40, (unsigned long )(& arr_2d[i___0][j___0]), (long long )arr_2d[i___0][j___0]);
#line 16
      printf((char const   * __restrict  )"%d", arr_2d[i___0][j___0]);
      __CrestClearStack(41);
      __CrestLoad(44, (unsigned long )(& j___0), (long long )j___0);
      __CrestLoad(43, (unsigned long )0, (long long )1);
      __CrestApply2(42, 0, (long long )(j___0 + 1));
      __CrestStore(45, (unsigned long )(& j___0));
#line 15
      j___0 ++;
    }
    while_break___2: /* CIL Label */ ;
    }
    __CrestLoad(48, (unsigned long )(& i___0), (long long )i___0);
    __CrestLoad(47, (unsigned long )0, (long long )1);
    __CrestApply2(46, 0, (long long )(i___0 + 1));
    __CrestStore(49, (unsigned long )(& i___0));
#line 14
    i___0 ++;
  }
  while_break___1: /* CIL Label */ 
  __CrestLoad(50, (unsigned long )0, (long long )0);
  __CrestStore(51, (unsigned long )(& __retres7));
#line 19
  __retres7 = 0;
  __CrestLoad(52, (unsigned long )(& __retres7), (long long )__retres7);
  __CrestReturn(53);
#line 4
  return (__retres7);
}
}
void __globinit_example_Array(void) 
{ 


  {
  __CrestInit();
}
}
