/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 315 "./b_tree.c"
void __globinit_b_tree(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 212 "/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h"
typedef unsigned long size_t;
#line 9 "./b_tree.c"
struct btreeNode {
   int val[5] ;
   int count ;
   struct btreeNode *link[5] ;
};
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 466 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
#line 483
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 202 "/home/hyorm1226/Development/crest-0.1.2/bin/../include/crest.h"
extern void __CrestInt(int *x )  __attribute__((__crest_skip__)) ;
#line 14 "./b_tree.c"
struct btreeNode *root  ;
#line 17 "./b_tree.c"
struct btreeNode *createNode(int val , struct btreeNode *child ) 
{ 
  struct btreeNode *newNode ;
  void *tmp ;

  {
  __CrestCall(2, 1);
  __CrestStore(1, (unsigned long )(& val));
  __CrestLoad(3, (unsigned long )0, (long long )sizeof(struct btreeNode ));
#line 19
  tmp = malloc(sizeof(struct btreeNode ));
  __CrestClearStack(4);
#line 19
  newNode = (struct btreeNode *)tmp;
  __CrestLoad(5, (unsigned long )(& val), (long long )val);
  __CrestStore(6, (unsigned long )(& newNode->val[1]));
#line 20
  newNode->val[1] = val;
  __CrestLoad(7, (unsigned long )0, (long long )1);
  __CrestStore(8, (unsigned long )(& newNode->count));
#line 21
  newNode->count = 1;
#line 22
  newNode->link[0] = root;
#line 23
  newNode->link[1] = child;
  {
  __CrestReturn(9);
#line 24
  return (newNode);
  }
}
}
#line 28 "./b_tree.c"
void addValToNode(int val , int pos , struct btreeNode *node , struct btreeNode *child ) 
{ 
  int j ;

  {
  __CrestCall(12, 2);
  __CrestStore(11, (unsigned long )(& pos));
  __CrestStore(10, (unsigned long )(& val));
  __CrestLoad(13, (unsigned long )(& node->count), (long long )node->count);
  __CrestStore(14, (unsigned long )(& j));
#line 30
  j = node->count;
  {
#line 31
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(17, (unsigned long )(& j), (long long )j);
    __CrestLoad(16, (unsigned long )(& pos), (long long )pos);
    __CrestApply2(15, 14, (long long )(j > pos));
#line 31
    if (j > pos) {
      __CrestBranch(18, 8, 1);

    } else {
      __CrestBranch(19, 9, 0);
#line 31
      goto while_break;
    }
    }
    __CrestLoad(20, (unsigned long )(& node->val[j]), (long long )node->val[j]);
    __CrestStore(21, (unsigned long )(& node->val[j + 1]));
#line 32
    node->val[j + 1] = node->val[j];
#line 33
    node->link[j + 1] = node->link[j];
    __CrestLoad(24, (unsigned long )(& j), (long long )j);
    __CrestLoad(23, (unsigned long )0, (long long )1);
    __CrestApply2(22, 1, (long long )(j - 1));
    __CrestStore(25, (unsigned long )(& j));
#line 34
    j --;
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(26, (unsigned long )(& val), (long long )val);
  __CrestStore(27, (unsigned long )(& node->val[j + 1]));
#line 36
  node->val[j + 1] = val;
#line 37
  node->link[j + 1] = child;
  __CrestLoad(30, (unsigned long )(& node->count), (long long )node->count);
  __CrestLoad(29, (unsigned long )0, (long long )1);
  __CrestApply2(28, 0, (long long )(node->count + 1));
  __CrestStore(31, (unsigned long )(& node->count));
#line 38
  (node->count) ++;

  {
  __CrestReturn(32);
#line 28
  return;
  }
}
}
#line 42 "./b_tree.c"
void splitNode(int val , int *pval , int pos , struct btreeNode *node , struct btreeNode *child ,
               struct btreeNode **newNode ) 
{ 
  int median ;
  int j ;
  void *tmp ;
  struct btreeNode *mem_10 ;
  struct btreeNode *mem_11 ;
  struct btreeNode *mem_12 ;
  struct btreeNode *mem_13 ;

  {
  __CrestCall(35, 3);
  __CrestStore(34, (unsigned long )(& pos));
  __CrestStore(33, (unsigned long )(& val));
  {
  __CrestLoad(38, (unsigned long )(& pos), (long long )pos);
  __CrestLoad(37, (unsigned long )0, (long long )2);
  __CrestApply2(36, 14, (long long )(pos > 2));
#line 46
  if (pos > 2) {
    __CrestBranch(39, 16, 1);
    __CrestLoad(41, (unsigned long )0, (long long )3);
    __CrestStore(42, (unsigned long )(& median));
#line 47
    median = 3;
  } else {
    __CrestBranch(40, 17, 0);
    __CrestLoad(43, (unsigned long )0, (long long )2);
    __CrestStore(44, (unsigned long )(& median));
#line 49
    median = 2;
  }
  }
  __CrestLoad(45, (unsigned long )0, (long long )sizeof(struct btreeNode ));
#line 51
  tmp = malloc(sizeof(struct btreeNode ));
  __CrestClearStack(46);
#line 51
  *newNode = (struct btreeNode *)tmp;
  __CrestLoad(49, (unsigned long )(& median), (long long )median);
  __CrestLoad(48, (unsigned long )0, (long long )1);
  __CrestApply2(47, 0, (long long )(median + 1));
  __CrestStore(50, (unsigned long )(& j));
#line 52
  j = median + 1;
  {
#line 53
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(53, (unsigned long )(& j), (long long )j);
    __CrestLoad(52, (unsigned long )0, (long long )4);
    __CrestApply2(51, 15, (long long )(j <= 4));
#line 53
    if (j <= 4) {
      __CrestBranch(54, 23, 1);

    } else {
      __CrestBranch(55, 24, 0);
#line 53
      goto while_break;
    }
    }
#line 54
    mem_10 = *newNode;
    __CrestLoad(56, (unsigned long )(& node->val[j]), (long long )node->val[j]);
    __CrestStore(57, (unsigned long )(& mem_10->val[j - median]));
#line 54
    mem_10->val[j - median] = node->val[j];
#line 55
    mem_11 = *newNode;
#line 55
    mem_11->link[j - median] = node->link[j];
    __CrestLoad(60, (unsigned long )(& j), (long long )j);
    __CrestLoad(59, (unsigned long )0, (long long )1);
    __CrestApply2(58, 0, (long long )(j + 1));
    __CrestStore(61, (unsigned long )(& j));
#line 56
    j ++;
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(62, (unsigned long )(& median), (long long )median);
  __CrestStore(63, (unsigned long )(& node->count));
#line 58
  node->count = median;
#line 59
  mem_12 = *newNode;
  __CrestLoad(66, (unsigned long )0, (long long )4);
  __CrestLoad(65, (unsigned long )(& median), (long long )median);
  __CrestApply2(64, 1, (long long )(4 - median));
  __CrestStore(67, (unsigned long )(& mem_12->count));
#line 59
  mem_12->count = 4 - median;
  {
  __CrestLoad(70, (unsigned long )(& pos), (long long )pos);
  __CrestLoad(69, (unsigned long )0, (long long )2);
  __CrestApply2(68, 15, (long long )(pos <= 2));
#line 61
  if (pos <= 2) {
    __CrestBranch(71, 29, 1);
    __CrestLoad(73, (unsigned long )(& val), (long long )val);
    __CrestLoad(74, (unsigned long )(& pos), (long long )pos);
#line 62
    addValToNode(val, pos, node, child);
    __CrestClearStack(75);
  } else {
    __CrestBranch(72, 30, 0);
    __CrestLoad(76, (unsigned long )(& val), (long long )val);
    __CrestLoad(79, (unsigned long )(& pos), (long long )pos);
    __CrestLoad(78, (unsigned long )(& median), (long long )median);
    __CrestApply2(77, 1, (long long )(pos - median));
#line 64
    addValToNode(val, pos - median, *newNode, child);
    __CrestClearStack(80);
  }
  }
  __CrestLoad(81, (unsigned long )(& node->val[node->count]), (long long )node->val[node->count]);
  __CrestStore(82, (unsigned long )pval);
#line 66
  *pval = node->val[node->count];
#line 67
  mem_13 = *newNode;
#line 67
  mem_13->link[0] = node->link[node->count];
  __CrestLoad(85, (unsigned long )(& node->count), (long long )node->count);
  __CrestLoad(84, (unsigned long )0, (long long )1);
  __CrestApply2(83, 1, (long long )(node->count - 1));
  __CrestStore(86, (unsigned long )(& node->count));
#line 68
  (node->count) --;

  {
  __CrestReturn(87);
#line 42
  return;
  }
}
}
#line 72 "./b_tree.c"
int setValueInNode(int val , int *pval , struct btreeNode *node , struct btreeNode **child ) 
{ 
  int pos ;
  int tmp ;
  int __retres7 ;

  {
  __CrestCall(89, 4);
  __CrestStore(88, (unsigned long )(& val));
  {
  __CrestLoad(92, (unsigned long )(& node), (long long )((unsigned long )node));
  __CrestLoad(91, (unsigned long )0, (long long )0);
  __CrestApply2(90, 12, (long long )(node == 0));
#line 76
  if (node == 0) {
    __CrestBranch(93, 35, 1);
    __CrestLoad(95, (unsigned long )(& val), (long long )val);
    __CrestStore(96, (unsigned long )pval);
#line 77
    *pval = val;
#line 78
    *child = (struct btreeNode *)((void *)0);
    __CrestLoad(97, (unsigned long )0, (long long )1);
    __CrestStore(98, (unsigned long )(& __retres7));
#line 79
    __retres7 = 1;
#line 79
    goto return_label;
  } else {
    __CrestBranch(94, 38, 0);

  }
  }
  {
  __CrestLoad(101, (unsigned long )(& val), (long long )val);
  __CrestLoad(100, (unsigned long )(& node->val[1]), (long long )node->val[1]);
  __CrestApply2(99, 16, (long long )(val < node->val[1]));
#line 82
  if (val < node->val[1]) {
    __CrestBranch(102, 40, 1);
    __CrestLoad(104, (unsigned long )0, (long long )0);
    __CrestStore(105, (unsigned long )(& pos));
#line 83
    pos = 0;
  } else {
    __CrestBranch(103, 41, 0);
    __CrestLoad(106, (unsigned long )(& node->count), (long long )node->count);
    __CrestStore(107, (unsigned long )(& pos));
#line 85
    pos = node->count;
    {
#line 85
    while (1) {
      while_continue: /* CIL Label */ ;
      {
      __CrestLoad(110, (unsigned long )(& val), (long long )val);
      __CrestLoad(109, (unsigned long )(& node->val[pos]), (long long )node->val[pos]);
      __CrestApply2(108, 16, (long long )(val < node->val[pos]));
#line 85
      if (val < node->val[pos]) {
        __CrestBranch(111, 46, 1);
        {
        __CrestLoad(115, (unsigned long )(& pos), (long long )pos);
        __CrestLoad(114, (unsigned long )0, (long long )1);
        __CrestApply2(113, 14, (long long )(pos > 1));
#line 85
        if (pos > 1) {
          __CrestBranch(116, 47, 1);

        } else {
          __CrestBranch(117, 48, 0);
#line 85
          goto while_break;
        }
        }
      } else {
        __CrestBranch(112, 49, 0);
#line 85
        goto while_break;
      }
      }
      __CrestLoad(120, (unsigned long )(& pos), (long long )pos);
      __CrestLoad(119, (unsigned long )0, (long long )1);
      __CrestApply2(118, 1, (long long )(pos - 1));
      __CrestStore(121, (unsigned long )(& pos));
#line 85
      pos --;
    }
    while_break: /* CIL Label */ ;
    }
    {
    __CrestLoad(124, (unsigned long )(& val), (long long )val);
    __CrestLoad(123, (unsigned long )(& node->val[pos]), (long long )node->val[pos]);
    __CrestApply2(122, 12, (long long )(val == node->val[pos]));
#line 87
    if (val == node->val[pos]) {
      __CrestBranch(125, 53, 1);
      __CrestLoad(127, (unsigned long )0, (long long )0);
      __CrestStore(128, (unsigned long )(& __retres7));
#line 89
      __retres7 = 0;
#line 89
      goto return_label;
    } else {
      __CrestBranch(126, 55, 0);

    }
    }
  }
  }
  __CrestLoad(129, (unsigned long )(& val), (long long )val);
#line 92
  tmp = setValueInNode(val, pval, node->link[pos], child);
  __CrestHandleReturn(131, (long long )tmp);
  __CrestStore(130, (unsigned long )(& tmp));
  {
  __CrestLoad(134, (unsigned long )(& tmp), (long long )tmp);
  __CrestLoad(133, (unsigned long )0, (long long )0);
  __CrestApply2(132, 13, (long long )(tmp != 0));
#line 92
  if (tmp != 0) {
    __CrestBranch(135, 58, 1);
    {
    __CrestLoad(139, (unsigned long )(& node->count), (long long )node->count);
    __CrestLoad(138, (unsigned long )0, (long long )4);
    __CrestApply2(137, 16, (long long )(node->count < 4));
#line 93
    if (node->count < 4) {
      __CrestBranch(140, 59, 1);
      __CrestLoad(142, (unsigned long )pval, (long long )*pval);
      __CrestLoad(143, (unsigned long )(& pos), (long long )pos);
#line 94
      addValToNode(*pval, pos, node, *child);
      __CrestClearStack(144);
    } else {
      __CrestBranch(141, 60, 0);
      __CrestLoad(145, (unsigned long )pval, (long long )*pval);
      __CrestLoad(146, (unsigned long )(& pos), (long long )pos);
#line 96
      splitNode(*pval, pval, pos, node, *child, child);
      __CrestClearStack(147);
      __CrestLoad(148, (unsigned long )0, (long long )1);
      __CrestStore(149, (unsigned long )(& __retres7));
#line 97
      __retres7 = 1;
#line 97
      goto return_label;
    }
    }
  } else {
    __CrestBranch(136, 63, 0);

  }
  }
  __CrestLoad(150, (unsigned long )0, (long long )0);
  __CrestStore(151, (unsigned long )(& __retres7));
#line 100
  __retres7 = 0;
  return_label: /* CIL Label */ 
  {
  __CrestLoad(152, (unsigned long )(& __retres7), (long long )__retres7);
  __CrestReturn(153);
#line 72
  return (__retres7);
  }
}
}
#line 104 "./b_tree.c"
void insertion(int val ) 
{ 
  int flag ;
  int i ;
  struct btreeNode *child ;

  {
  __CrestCall(155, 5);
  __CrestStore(154, (unsigned long )(& val));
  __CrestLoad(156, (unsigned long )(& val), (long long )val);
#line 108
  flag = setValueInNode(val, & i, root, & child);
  __CrestHandleReturn(158, (long long )flag);
  __CrestStore(157, (unsigned long )(& flag));
  {
  __CrestLoad(161, (unsigned long )(& flag), (long long )flag);
  __CrestLoad(160, (unsigned long )0, (long long )0);
  __CrestApply2(159, 13, (long long )(flag != 0));
#line 109
  if (flag != 0) {
    __CrestBranch(162, 68, 1);
    __CrestLoad(164, (unsigned long )(& i), (long long )i);
#line 110
    root = createNode(i, child);
    __CrestClearStack(165);
  } else {
    __CrestBranch(163, 69, 0);

  }
  }

  {
  __CrestReturn(166);
#line 104
  return;
  }
}
}
#line 114 "./b_tree.c"
void copySuccessor(struct btreeNode *myNode , int pos ) 
{ 
  struct btreeNode *dummy ;

  {
  __CrestCall(168, 6);
  __CrestStore(167, (unsigned long )(& pos));
#line 116
  dummy = myNode->link[pos];
  {
#line 118
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(171, (unsigned long )(& dummy->link[0]), (long long )((unsigned long )dummy->link[0]));
    __CrestLoad(170, (unsigned long )0, (long long )((unsigned long )((void *)0)));
    __CrestApply2(169, 13, (long long )((unsigned long )dummy->link[0] != (unsigned long )((void *)0)));
#line 118
    if ((unsigned long )dummy->link[0] != (unsigned long )((void *)0)) {
      __CrestBranch(172, 77, 1);

    } else {
      __CrestBranch(173, 78, 0);
#line 118
      goto while_break;
    }
    }
#line 119
    dummy = dummy->link[0];
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(174, (unsigned long )(& dummy->val[1]), (long long )dummy->val[1]);
  __CrestStore(175, (unsigned long )(& myNode->val[pos]));
#line 120
  myNode->val[pos] = dummy->val[1];

  {
  __CrestReturn(176);
#line 114
  return;
  }
}
}
#line 125 "./b_tree.c"
void removeVal(struct btreeNode *myNode , int pos ) 
{ 
  int i ;

  {
  __CrestCall(178, 7);
  __CrestStore(177, (unsigned long )(& pos));
  __CrestLoad(181, (unsigned long )(& pos), (long long )pos);
  __CrestLoad(180, (unsigned long )0, (long long )1);
  __CrestApply2(179, 0, (long long )(pos + 1));
  __CrestStore(182, (unsigned long )(& i));
#line 126
  i = pos + 1;
  {
#line 127
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(185, (unsigned long )(& i), (long long )i);
    __CrestLoad(184, (unsigned long )(& myNode->count), (long long )myNode->count);
    __CrestApply2(183, 15, (long long )(i <= myNode->count));
#line 127
    if (i <= myNode->count) {
      __CrestBranch(186, 89, 1);

    } else {
      __CrestBranch(187, 90, 0);
#line 127
      goto while_break;
    }
    }
    __CrestLoad(188, (unsigned long )(& myNode->val[i]), (long long )myNode->val[i]);
    __CrestStore(189, (unsigned long )(& myNode->val[i - 1]));
#line 128
    myNode->val[i - 1] = myNode->val[i];
#line 129
    myNode->link[i - 1] = myNode->link[i];
    __CrestLoad(192, (unsigned long )(& i), (long long )i);
    __CrestLoad(191, (unsigned long )0, (long long )1);
    __CrestApply2(190, 0, (long long )(i + 1));
    __CrestStore(193, (unsigned long )(& i));
#line 130
    i ++;
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(196, (unsigned long )(& myNode->count), (long long )myNode->count);
  __CrestLoad(195, (unsigned long )0, (long long )1);
  __CrestApply2(194, 1, (long long )(myNode->count - 1));
  __CrestStore(197, (unsigned long )(& myNode->count));
#line 132
  (myNode->count) --;

  {
  __CrestReturn(198);
#line 125
  return;
  }
}
}
#line 136 "./b_tree.c"
void doRightShift(struct btreeNode *myNode , int pos ) 
{ 
  struct btreeNode *x ;
  int j ;

  {
  __CrestCall(200, 8);
  __CrestStore(199, (unsigned long )(& pos));
#line 137
  x = myNode->link[pos];
  __CrestLoad(201, (unsigned long )(& x->count), (long long )x->count);
  __CrestStore(202, (unsigned long )(& j));
#line 138
  j = x->count;
  {
#line 140
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(205, (unsigned long )(& j), (long long )j);
    __CrestLoad(204, (unsigned long )0, (long long )0);
    __CrestApply2(203, 14, (long long )(j > 0));
#line 140
    if (j > 0) {
      __CrestBranch(206, 101, 1);

    } else {
      __CrestBranch(207, 102, 0);
#line 140
      goto while_break;
    }
    }
    __CrestLoad(208, (unsigned long )(& x->val[j]), (long long )x->val[j]);
    __CrestStore(209, (unsigned long )(& x->val[j + 1]));
#line 141
    x->val[j + 1] = x->val[j];
#line 142
    x->link[j + 1] = x->link[j];
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(210, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
  __CrestStore(211, (unsigned long )(& x->val[1]));
#line 144
  x->val[1] = myNode->val[pos];
#line 145
  x->link[1] = x->link[0];
  __CrestLoad(214, (unsigned long )(& x->count), (long long )x->count);
  __CrestLoad(213, (unsigned long )0, (long long )1);
  __CrestApply2(212, 0, (long long )(x->count + 1));
  __CrestStore(215, (unsigned long )(& x->count));
#line 146
  (x->count) ++;
#line 148
  x = myNode->link[pos - 1];
  __CrestLoad(216, (unsigned long )(& x->val[x->count]), (long long )x->val[x->count]);
  __CrestStore(217, (unsigned long )(& myNode->val[pos]));
#line 149
  myNode->val[pos] = x->val[x->count];
#line 150
  myNode->link[pos] = x->link[x->count];
  __CrestLoad(220, (unsigned long )(& x->count), (long long )x->count);
  __CrestLoad(219, (unsigned long )0, (long long )1);
  __CrestApply2(218, 1, (long long )(x->count - 1));
  __CrestStore(221, (unsigned long )(& x->count));
#line 151
  (x->count) --;

  {
  __CrestReturn(222);
#line 136
  return;
  }
}
}
#line 156 "./b_tree.c"
void doLeftShift(struct btreeNode *myNode , int pos ) 
{ 
  int j ;
  struct btreeNode *x ;
  struct btreeNode *mem_5 ;

  {
  __CrestCall(224, 9);
  __CrestStore(223, (unsigned long )(& pos));
  __CrestLoad(225, (unsigned long )0, (long long )1);
  __CrestStore(226, (unsigned long )(& j));
#line 157
  j = 1;
#line 158
  x = myNode->link[pos - 1];
  __CrestLoad(229, (unsigned long )(& x->count), (long long )x->count);
  __CrestLoad(228, (unsigned long )0, (long long )1);
  __CrestApply2(227, 0, (long long )(x->count + 1));
  __CrestStore(230, (unsigned long )(& x->count));
#line 160
  (x->count) ++;
  __CrestLoad(231, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
  __CrestStore(232, (unsigned long )(& x->val[x->count]));
#line 161
  x->val[x->count] = myNode->val[pos];
#line 162
  mem_5 = myNode->link[pos];
#line 162
  x->link[x->count] = mem_5->link[0];
#line 164
  x = myNode->link[pos];
  __CrestLoad(233, (unsigned long )(& x->val[1]), (long long )x->val[1]);
  __CrestStore(234, (unsigned long )(& myNode->val[pos]));
#line 165
  myNode->val[pos] = x->val[1];
#line 166
  x->link[0] = x->link[1];
  __CrestLoad(237, (unsigned long )(& x->count), (long long )x->count);
  __CrestLoad(236, (unsigned long )0, (long long )1);
  __CrestApply2(235, 1, (long long )(x->count - 1));
  __CrestStore(238, (unsigned long )(& x->count));
#line 167
  (x->count) --;
  {
#line 169
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(241, (unsigned long )(& j), (long long )j);
    __CrestLoad(240, (unsigned long )(& x->count), (long long )x->count);
    __CrestApply2(239, 15, (long long )(j <= x->count));
#line 169
    if (j <= x->count) {
      __CrestBranch(242, 113, 1);

    } else {
      __CrestBranch(243, 114, 0);
#line 169
      goto while_break;
    }
    }
    __CrestLoad(244, (unsigned long )(& x->val[j + 1]), (long long )x->val[j + 1]);
    __CrestStore(245, (unsigned long )(& x->val[j]));
#line 170
    x->val[j] = x->val[j + 1];
#line 171
    x->link[j] = x->link[j + 1];
    __CrestLoad(248, (unsigned long )(& j), (long long )j);
    __CrestLoad(247, (unsigned long )0, (long long )1);
    __CrestApply2(246, 0, (long long )(j + 1));
    __CrestStore(249, (unsigned long )(& j));
#line 172
    j ++;
  }
  while_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(250);
#line 156
  return;
  }
}
}
#line 178 "./b_tree.c"
void mergeNodes(struct btreeNode *myNode , int pos ) 
{ 
  int j ;
  struct btreeNode *x1 ;
  struct btreeNode *x2 ;

  {
  __CrestCall(252, 10);
  __CrestStore(251, (unsigned long )(& pos));
  __CrestLoad(253, (unsigned long )0, (long long )1);
  __CrestStore(254, (unsigned long )(& j));
#line 179
  j = 1;
#line 180
  x1 = myNode->link[pos];
#line 180
  x2 = myNode->link[pos - 1];
  __CrestLoad(257, (unsigned long )(& x2->count), (long long )x2->count);
  __CrestLoad(256, (unsigned long )0, (long long )1);
  __CrestApply2(255, 0, (long long )(x2->count + 1));
  __CrestStore(258, (unsigned long )(& x2->count));
#line 182
  (x2->count) ++;
  __CrestLoad(259, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
  __CrestStore(260, (unsigned long )(& x2->val[x2->count]));
#line 183
  x2->val[x2->count] = myNode->val[pos];
#line 184
  x2->link[x2->count] = myNode->link[0];
  {
#line 186
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(263, (unsigned long )(& j), (long long )j);
    __CrestLoad(262, (unsigned long )(& x1->count), (long long )x1->count);
    __CrestApply2(261, 15, (long long )(j <= x1->count));
#line 186
    if (j <= x1->count) {
      __CrestBranch(264, 124, 1);

    } else {
      __CrestBranch(265, 125, 0);
#line 186
      goto while_break;
    }
    }
    __CrestLoad(268, (unsigned long )(& x2->count), (long long )x2->count);
    __CrestLoad(267, (unsigned long )0, (long long )1);
    __CrestApply2(266, 0, (long long )(x2->count + 1));
    __CrestStore(269, (unsigned long )(& x2->count));
#line 187
    (x2->count) ++;
    __CrestLoad(270, (unsigned long )(& x1->val[j]), (long long )x1->val[j]);
    __CrestStore(271, (unsigned long )(& x2->val[x2->count]));
#line 188
    x2->val[x2->count] = x1->val[j];
#line 189
    x2->link[x2->count] = x1->link[j];
    __CrestLoad(274, (unsigned long )(& j), (long long )j);
    __CrestLoad(273, (unsigned long )0, (long long )1);
    __CrestApply2(272, 0, (long long )(j + 1));
    __CrestStore(275, (unsigned long )(& j));
#line 190
    j ++;
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(276, (unsigned long )(& pos), (long long )pos);
  __CrestStore(277, (unsigned long )(& j));
#line 193
  j = pos;
  {
#line 194
  while (1) {
    while_continue___0: /* CIL Label */ ;
    {
    __CrestLoad(280, (unsigned long )(& j), (long long )j);
    __CrestLoad(279, (unsigned long )(& myNode->count), (long long )myNode->count);
    __CrestApply2(278, 16, (long long )(j < myNode->count));
#line 194
    if (j < myNode->count) {
      __CrestBranch(281, 133, 1);

    } else {
      __CrestBranch(282, 134, 0);
#line 194
      goto while_break___0;
    }
    }
    __CrestLoad(283, (unsigned long )(& myNode->val[j + 1]), (long long )myNode->val[j + 1]);
    __CrestStore(284, (unsigned long )(& myNode->val[j]));
#line 195
    myNode->val[j] = myNode->val[j + 1];
#line 196
    myNode->link[j] = myNode->link[j + 1];
    __CrestLoad(287, (unsigned long )(& j), (long long )j);
    __CrestLoad(286, (unsigned long )0, (long long )1);
    __CrestApply2(285, 0, (long long )(j + 1));
    __CrestStore(288, (unsigned long )(& j));
#line 197
    j ++;
  }
  while_break___0: /* CIL Label */ ;
  }
  __CrestLoad(291, (unsigned long )(& myNode->count), (long long )myNode->count);
  __CrestLoad(290, (unsigned long )0, (long long )1);
  __CrestApply2(289, 1, (long long )(myNode->count - 1));
  __CrestStore(292, (unsigned long )(& myNode->count));
#line 199
  (myNode->count) --;
#line 200
  free((void *)x1);
  __CrestClearStack(293);

  {
  __CrestReturn(294);
#line 178
  return;
  }
}
}
#line 204 "./b_tree.c"
void adjustNode(struct btreeNode *myNode , int pos ) 
{ 
  struct btreeNode *mem_3 ;
  struct btreeNode *mem_4 ;
  struct btreeNode *mem_5 ;
  struct btreeNode *mem_6 ;

  {
  __CrestCall(296, 11);
  __CrestStore(295, (unsigned long )(& pos));
  {
  __CrestLoad(299, (unsigned long )(& pos), (long long )pos);
  __CrestLoad(298, (unsigned long )0, (long long )0);
  __CrestApply2(297, 12, (long long )(pos == 0));
#line 205
  if (pos == 0) {
    __CrestBranch(300, 141, 1);
    {
#line 206
    mem_3 = myNode->link[1];
    {
    __CrestLoad(304, (unsigned long )(& mem_3->count), (long long )mem_3->count);
    __CrestLoad(303, (unsigned long )0, (long long )2);
    __CrestApply2(302, 14, (long long )(mem_3->count > 2));
#line 206
    if (mem_3->count > 2) {
      __CrestBranch(305, 144, 1);
      __CrestLoad(307, (unsigned long )0, (long long )1);
#line 207
      doLeftShift(myNode, 1);
      __CrestClearStack(308);
    } else {
      __CrestBranch(306, 145, 0);
      __CrestLoad(309, (unsigned long )0, (long long )1);
#line 209
      mergeNodes(myNode, 1);
      __CrestClearStack(310);
    }
    }
    }
  } else {
    __CrestBranch(301, 146, 0);
    {
    __CrestLoad(313, (unsigned long )(& myNode->count), (long long )myNode->count);
    __CrestLoad(312, (unsigned long )(& pos), (long long )pos);
    __CrestApply2(311, 13, (long long )(myNode->count != pos));
#line 212
    if (myNode->count != pos) {
      __CrestBranch(314, 147, 1);
      {
#line 213
      mem_4 = myNode->link[pos - 1];
      {
      __CrestLoad(318, (unsigned long )(& mem_4->count), (long long )mem_4->count);
      __CrestLoad(317, (unsigned long )0, (long long )2);
      __CrestApply2(316, 14, (long long )(mem_4->count > 2));
#line 213
      if (mem_4->count > 2) {
        __CrestBranch(319, 150, 1);
        __CrestLoad(321, (unsigned long )(& pos), (long long )pos);
#line 214
        doRightShift(myNode, pos);
        __CrestClearStack(322);
      } else {
        __CrestBranch(320, 151, 0);
        {
#line 216
        mem_5 = myNode->link[pos + 1];
        {
        __CrestLoad(325, (unsigned long )(& mem_5->count), (long long )mem_5->count);
        __CrestLoad(324, (unsigned long )0, (long long )2);
        __CrestApply2(323, 14, (long long )(mem_5->count > 2));
#line 216
        if (mem_5->count > 2) {
          __CrestBranch(326, 154, 1);
          __CrestLoad(330, (unsigned long )(& pos), (long long )pos);
          __CrestLoad(329, (unsigned long )0, (long long )1);
          __CrestApply2(328, 0, (long long )(pos + 1));
#line 217
          doLeftShift(myNode, pos + 1);
          __CrestClearStack(331);
        } else {
          __CrestBranch(327, 155, 0);
          __CrestLoad(332, (unsigned long )(& pos), (long long )pos);
#line 219
          mergeNodes(myNode, pos);
          __CrestClearStack(333);
        }
        }
        }
      }
      }
      }
    } else {
      __CrestBranch(315, 156, 0);
      {
#line 223
      mem_6 = myNode->link[pos - 1];
      {
      __CrestLoad(336, (unsigned long )(& mem_6->count), (long long )mem_6->count);
      __CrestLoad(335, (unsigned long )0, (long long )2);
      __CrestApply2(334, 14, (long long )(mem_6->count > 2));
#line 223
      if (mem_6->count > 2) {
        __CrestBranch(337, 159, 1);
        __CrestLoad(339, (unsigned long )(& pos), (long long )pos);
#line 224
        doRightShift(myNode, pos);
        __CrestClearStack(340);
      } else {
        __CrestBranch(338, 160, 0);
        __CrestLoad(341, (unsigned long )(& pos), (long long )pos);
#line 226
        mergeNodes(myNode, pos);
        __CrestClearStack(342);
      }
      }
      }
    }
    }
  }
  }

  {
  __CrestReturn(343);
#line 204
  return;
  }
}
}
#line 232 "./b_tree.c"
int delValFromNode(int val , struct btreeNode *myNode ) 
{ 
  int pos ;
  int flag ;
  struct btreeNode *mem_5 ;

  {
  __CrestCall(345, 12);
  __CrestStore(344, (unsigned long )(& val));
  __CrestLoad(346, (unsigned long )0, (long long )0);
  __CrestStore(347, (unsigned long )(& flag));
#line 233
  flag = 0;
  {
  __CrestLoad(350, (unsigned long )(& myNode), (long long )((unsigned long )myNode));
  __CrestLoad(349, (unsigned long )0, (long long )0);
  __CrestApply2(348, 13, (long long )(myNode != 0));
#line 234
  if (myNode != 0) {
    __CrestBranch(351, 165, 1);
    {
    __CrestLoad(355, (unsigned long )(& val), (long long )val);
    __CrestLoad(354, (unsigned long )(& myNode->val[1]), (long long )myNode->val[1]);
    __CrestApply2(353, 16, (long long )(val < myNode->val[1]));
#line 235
    if (val < myNode->val[1]) {
      __CrestBranch(356, 166, 1);
      __CrestLoad(358, (unsigned long )0, (long long )0);
      __CrestStore(359, (unsigned long )(& pos));
#line 236
      pos = 0;
      __CrestLoad(360, (unsigned long )0, (long long )0);
      __CrestStore(361, (unsigned long )(& flag));
#line 237
      flag = 0;
    } else {
      __CrestBranch(357, 167, 0);
      __CrestLoad(362, (unsigned long )(& myNode->count), (long long )myNode->count);
      __CrestStore(363, (unsigned long )(& pos));
#line 239
      pos = myNode->count;
      {
#line 239
      while (1) {
        while_continue: /* CIL Label */ ;
        {
        __CrestLoad(366, (unsigned long )(& val), (long long )val);
        __CrestLoad(365, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
        __CrestApply2(364, 16, (long long )(val < myNode->val[pos]));
#line 239
        if (val < myNode->val[pos]) {
          __CrestBranch(367, 172, 1);
          {
          __CrestLoad(371, (unsigned long )(& pos), (long long )pos);
          __CrestLoad(370, (unsigned long )0, (long long )1);
          __CrestApply2(369, 14, (long long )(pos > 1));
#line 239
          if (pos > 1) {
            __CrestBranch(372, 173, 1);

          } else {
            __CrestBranch(373, 174, 0);
#line 239
            goto while_break;
          }
          }
        } else {
          __CrestBranch(368, 175, 0);
#line 239
          goto while_break;
        }
        }
        __CrestLoad(376, (unsigned long )(& pos), (long long )pos);
        __CrestLoad(375, (unsigned long )0, (long long )1);
        __CrestApply2(374, 1, (long long )(pos - 1));
        __CrestStore(377, (unsigned long )(& pos));
#line 239
        pos --;
      }
      while_break: /* CIL Label */ ;
      }
      {
      __CrestLoad(380, (unsigned long )(& val), (long long )val);
      __CrestLoad(379, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
      __CrestApply2(378, 12, (long long )(val == myNode->val[pos]));
#line 241
      if (val == myNode->val[pos]) {
        __CrestBranch(381, 179, 1);
        __CrestLoad(383, (unsigned long )0, (long long )1);
        __CrestStore(384, (unsigned long )(& flag));
#line 242
        flag = 1;
      } else {
        __CrestBranch(382, 180, 0);
        __CrestLoad(385, (unsigned long )0, (long long )0);
        __CrestStore(386, (unsigned long )(& flag));
#line 244
        flag = 0;
      }
      }
    }
    }
    {
    __CrestLoad(389, (unsigned long )(& flag), (long long )flag);
    __CrestLoad(388, (unsigned long )0, (long long )0);
    __CrestApply2(387, 13, (long long )(flag != 0));
#line 247
    if (flag != 0) {
      __CrestBranch(390, 182, 1);
      {
      __CrestLoad(394, (unsigned long )(& myNode->link[pos - 1]), (long long )((unsigned long )myNode->link[pos - 1]));
      __CrestLoad(393, (unsigned long )0, (long long )0);
      __CrestApply2(392, 13, (long long )(myNode->link[pos - 1] != 0));
#line 248
      if (myNode->link[pos - 1] != 0) {
        __CrestBranch(395, 183, 1);
        __CrestLoad(397, (unsigned long )(& pos), (long long )pos);
#line 249
        copySuccessor(myNode, pos);
        __CrestClearStack(398);
        __CrestLoad(399, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
#line 250
        flag = delValFromNode(myNode->val[pos], myNode->link[pos]);
        __CrestHandleReturn(401, (long long )flag);
        __CrestStore(400, (unsigned long )(& flag));
      } else {
        __CrestBranch(396, 184, 0);
        __CrestLoad(402, (unsigned long )(& pos), (long long )pos);
#line 255
        removeVal(myNode, pos);
        __CrestClearStack(403);
      }
      }
    } else {
      __CrestBranch(391, 185, 0);
      __CrestLoad(404, (unsigned long )(& val), (long long )val);
#line 258
      flag = delValFromNode(val, myNode->link[pos]);
      __CrestHandleReturn(406, (long long )flag);
      __CrestStore(405, (unsigned long )(& flag));
    }
    }
    {
    __CrestLoad(409, (unsigned long )(& myNode->link[pos]), (long long )((unsigned long )myNode->link[pos]));
    __CrestLoad(408, (unsigned long )0, (long long )0);
    __CrestApply2(407, 13, (long long )(myNode->link[pos] != 0));
#line 260
    if (myNode->link[pos] != 0) {
      __CrestBranch(410, 187, 1);
      {
#line 261
      mem_5 = myNode->link[pos];
      {
      __CrestLoad(414, (unsigned long )(& mem_5->count), (long long )mem_5->count);
      __CrestLoad(413, (unsigned long )0, (long long )2);
      __CrestApply2(412, 16, (long long )(mem_5->count < 2));
#line 261
      if (mem_5->count < 2) {
        __CrestBranch(415, 190, 1);
        __CrestLoad(417, (unsigned long )(& pos), (long long )pos);
#line 262
        adjustNode(myNode, pos);
        __CrestClearStack(418);
      } else {
        __CrestBranch(416, 191, 0);

      }
      }
      }
    } else {
      __CrestBranch(411, 192, 0);

    }
    }
  } else {
    __CrestBranch(352, 193, 0);

  }
  }
  {
  __CrestLoad(419, (unsigned long )(& flag), (long long )flag);
  __CrestReturn(420);
#line 265
  return (flag);
  }
}
}
#line 269 "./b_tree.c"
void deletion(int val , struct btreeNode *myNode ) 
{ 
  struct btreeNode *tmp ;
  int tmp___0 ;

  {
  __CrestCall(422, 13);
  __CrestStore(421, (unsigned long )(& val));
  __CrestLoad(423, (unsigned long )(& val), (long long )val);
#line 271
  tmp___0 = delValFromNode(val, myNode);
  __CrestHandleReturn(425, (long long )tmp___0);
  __CrestStore(424, (unsigned long )(& tmp___0));
  {
  __CrestLoad(428, (unsigned long )(& tmp___0), (long long )tmp___0);
  __CrestLoad(427, (unsigned long )0, (long long )0);
  __CrestApply2(426, 13, (long long )(tmp___0 != 0));
#line 271
  if (tmp___0 != 0) {
    __CrestBranch(429, 197, 1);
    {
    __CrestLoad(433, (unsigned long )(& myNode->count), (long long )myNode->count);
    __CrestLoad(432, (unsigned long )0, (long long )0);
    __CrestApply2(431, 12, (long long )(myNode->count == 0));
#line 275
    if (myNode->count == 0) {
      __CrestBranch(434, 198, 1);
#line 276
      tmp = myNode;
#line 277
      myNode = myNode->link[0];
#line 278
      free((void *)tmp);
      __CrestClearStack(436);
    } else {
      __CrestBranch(435, 199, 0);

    }
    }
  } else {
    __CrestBranch(430, 200, 0);

#line 273
    goto return_label;
  }
  }
#line 281
  root = myNode;

  return_label: /* CIL Label */ 
  {
  __CrestReturn(437);
#line 269
  return;
  }
}
}
#line 284 "./b_tree.c"
void searching(int val , int *pos , struct btreeNode *myNode ) 
{ 


  {
  __CrestCall(439, 14);
  __CrestStore(438, (unsigned long )(& val));
  {
  __CrestLoad(442, (unsigned long )(& myNode), (long long )((unsigned long )myNode));
  __CrestLoad(441, (unsigned long )0, (long long )0);
  __CrestApply2(440, 12, (long long )(myNode == 0));
#line 285
  if (myNode == 0) {
    __CrestBranch(443, 206, 1);

#line 286
    goto return_label;
  } else {
    __CrestBranch(444, 208, 0);

  }
  }
  {
  __CrestLoad(447, (unsigned long )(& val), (long long )val);
  __CrestLoad(446, (unsigned long )(& myNode->val[1]), (long long )myNode->val[1]);
  __CrestApply2(445, 16, (long long )(val < myNode->val[1]));
#line 289
  if (val < myNode->val[1]) {
    __CrestBranch(448, 210, 1);
    __CrestLoad(450, (unsigned long )0, (long long )0);
    __CrestStore(451, (unsigned long )pos);
#line 290
    *pos = 0;
  } else {
    __CrestBranch(449, 211, 0);
    __CrestLoad(452, (unsigned long )(& myNode->count), (long long )myNode->count);
    __CrestStore(453, (unsigned long )pos);
#line 292
    *pos = myNode->count;
    {
#line 292
    while (1) {
      while_continue: /* CIL Label */ ;
      {
      __CrestLoad(456, (unsigned long )(& val), (long long )val);
      __CrestLoad(455, (unsigned long )(& myNode->val[*pos]), (long long )myNode->val[*pos]);
      __CrestApply2(454, 16, (long long )(val < myNode->val[*pos]));
#line 292
      if (val < myNode->val[*pos]) {
        __CrestBranch(457, 216, 1);
        {
        __CrestLoad(461, (unsigned long )pos, (long long )*pos);
        __CrestLoad(460, (unsigned long )0, (long long )1);
        __CrestApply2(459, 14, (long long )(*pos > 1));
#line 292
        if (*pos > 1) {
          __CrestBranch(462, 217, 1);

        } else {
          __CrestBranch(463, 218, 0);
#line 292
          goto while_break;
        }
        }
      } else {
        __CrestBranch(458, 219, 0);
#line 292
        goto while_break;
      }
      }
      __CrestLoad(466, (unsigned long )pos, (long long )*pos);
      __CrestLoad(465, (unsigned long )0, (long long )1);
      __CrestApply2(464, 1, (long long )(*pos - 1));
      __CrestStore(467, (unsigned long )pos);
#line 292
      (*pos) --;
    }
    while_break: /* CIL Label */ ;
    }
    {
    __CrestLoad(470, (unsigned long )(& val), (long long )val);
    __CrestLoad(469, (unsigned long )(& myNode->val[*pos]), (long long )myNode->val[*pos]);
    __CrestApply2(468, 12, (long long )(val == myNode->val[*pos]));
#line 294
    if (val == myNode->val[*pos]) {
      __CrestBranch(471, 223, 1);

#line 296
      goto return_label;
    } else {
      __CrestBranch(472, 225, 0);

    }
    }
  }
  }
  __CrestLoad(473, (unsigned long )(& val), (long long )val);
#line 299
  searching(val, pos, myNode->link[*pos]);
  __CrestClearStack(474);

  return_label: /* CIL Label */ 
  {
  __CrestReturn(475);
#line 284
  return;
  }
}
}
#line 304 "./b_tree.c"
void traversal(struct btreeNode *myNode ) 
{ 
  int i ;

  {
  __CrestCall(476, 15);

  {
  __CrestLoad(479, (unsigned long )(& myNode), (long long )((unsigned long )myNode));
  __CrestLoad(478, (unsigned long )0, (long long )0);
  __CrestApply2(477, 13, (long long )(myNode != 0));
#line 306
  if (myNode != 0) {
    __CrestBranch(480, 230, 1);
    __CrestLoad(482, (unsigned long )0, (long long )0);
    __CrestStore(483, (unsigned long )(& i));
#line 307
    i = 0;
    {
#line 307
    while (1) {
      while_continue: /* CIL Label */ ;
      {
      __CrestLoad(486, (unsigned long )(& i), (long long )i);
      __CrestLoad(485, (unsigned long )(& myNode->count), (long long )myNode->count);
      __CrestApply2(484, 16, (long long )(i < myNode->count));
#line 307
      if (i < myNode->count) {
        __CrestBranch(487, 235, 1);

      } else {
        __CrestBranch(488, 236, 0);
#line 307
        goto while_break;
      }
      }
#line 308
      traversal(myNode->link[i]);
      __CrestClearStack(489);
      __CrestLoad(492, (unsigned long )(& i), (long long )i);
      __CrestLoad(491, (unsigned long )0, (long long )1);
      __CrestApply2(490, 0, (long long )(i + 1));
      __CrestStore(493, (unsigned long )(& i));
#line 307
      i ++;
    }
    while_break: /* CIL Label */ ;
    }
#line 311
    traversal(myNode->link[i]);
    __CrestClearStack(494);
  } else {
    __CrestBranch(481, 240, 0);

  }
  }

  {
  __CrestReturn(495);
#line 304
  return;
  }
}
}
#line 315 "./b_tree.c"
int main(void) 
{ 
  int val ;
  int ch ;
  int count ;
  int __retres5 ;

  {
  __globinit_b_tree();
  __CrestCall(496, 16);
  __CrestLoad(497, (unsigned long )0, (long long )0);
  __CrestStore(498, (unsigned long )(& count));
#line 318
  count = 0;
#line 319
  while (1) {
    while_continue: /* CIL Label */ ;
#line 320
    printf((char const   * __restrict  )"1. Insertion\t2. Deletion\n");
    __CrestClearStack(499);
#line 321
    printf((char const   * __restrict  )"3. Searching\t4. Traversal\n");
    __CrestClearStack(500);
#line 322
    printf((char const   * __restrict  )"5. Exit\nEnter your choice:");
    __CrestClearStack(501);
#line 324
    __CrestInt(& ch);
    __CrestLoad(504, (unsigned long )(& ch), (long long )ch);
    __CrestLoad(503, (unsigned long )0, (long long )10);
    __CrestApply2(502, 4, (long long )(ch % 10));
    __CrestStore(505, (unsigned long )(& ch));
#line 325
    ch %= 10;
    __CrestLoad(506, (unsigned long )(& ch), (long long )ch);
#line 326
    printf((char const   * __restrict  )"%d\n", ch);
    __CrestClearStack(507);
    {
    {
    __CrestLoad(510, (unsigned long )(& ch), (long long )ch);
    __CrestLoad(509, (unsigned long )0, (long long )1);
    __CrestApply2(508, 12, (long long )(ch == 1));
#line 328
    if (ch == 1) {
      __CrestBranch(511, 250, 1);
#line 328
      goto case_1;
    } else {
      __CrestBranch(512, 251, 0);

    }
    }
    {
    __CrestLoad(515, (unsigned long )(& ch), (long long )ch);
    __CrestLoad(514, (unsigned long )0, (long long )2);
    __CrestApply2(513, 12, (long long )(ch == 2));
#line 335
    if (ch == 2) {
      __CrestBranch(516, 253, 1);
#line 335
      goto case_2;
    } else {
      __CrestBranch(517, 254, 0);

    }
    }
    {
    __CrestLoad(520, (unsigned long )(& ch), (long long )ch);
    __CrestLoad(519, (unsigned long )0, (long long )3);
    __CrestApply2(518, 12, (long long )(ch == 3));
#line 342
    if (ch == 3) {
      __CrestBranch(521, 256, 1);
#line 342
      goto case_3;
    } else {
      __CrestBranch(522, 257, 0);

    }
    }
    {
    __CrestLoad(525, (unsigned long )(& ch), (long long )ch);
    __CrestLoad(524, (unsigned long )0, (long long )4);
    __CrestApply2(523, 12, (long long )(ch == 4));
#line 349
    if (ch == 4) {
      __CrestBranch(526, 259, 1);
#line 349
      goto case_4;
    } else {
      __CrestBranch(527, 260, 0);

    }
    }
    {
    __CrestLoad(530, (unsigned long )(& ch), (long long )ch);
    __CrestLoad(529, (unsigned long )0, (long long )5);
    __CrestApply2(528, 12, (long long )(ch == 5));
#line 352
    if (ch == 5) {
      __CrestBranch(531, 262, 1);
#line 352
      goto case_5;
    } else {
      __CrestBranch(532, 263, 0);

    }
    }
#line 354
    goto switch_default;
    case_1: /* CIL Label */ 
#line 329
    printf((char const   * __restrict  )"Enter your input:");
    __CrestClearStack(533);
#line 331
    __CrestInt(& val);
    __CrestLoad(534, (unsigned long )(& val), (long long )val);
#line 332
    printf((char const   * __restrict  )"%d\n", val);
    __CrestClearStack(535);
    __CrestLoad(536, (unsigned long )(& val), (long long )val);
#line 333
    insertion(val);
    __CrestClearStack(537);
#line 334
    goto switch_break;
    case_2: /* CIL Label */ 
#line 336
    printf((char const   * __restrict  )"Enter the element to delete:");
    __CrestClearStack(538);
#line 338
    __CrestInt(& val);
    __CrestLoad(539, (unsigned long )(& val), (long long )val);
#line 339
    printf((char const   * __restrict  )"%d\n", val);
    __CrestClearStack(540);
    __CrestLoad(541, (unsigned long )(& val), (long long )val);
#line 340
    deletion(val, root);
    __CrestClearStack(542);
#line 341
    goto switch_break;
    case_3: /* CIL Label */ 
#line 343
    printf((char const   * __restrict  )"Enter the element to search:");
    __CrestClearStack(543);
#line 345
    __CrestInt(& val);
    __CrestLoad(544, (unsigned long )(& val), (long long )val);
#line 346
    printf((char const   * __restrict  )"%d\n", val);
    __CrestClearStack(545);
    __CrestLoad(546, (unsigned long )(& val), (long long )val);
#line 347
    searching(val, & ch, root);
    __CrestClearStack(547);
#line 348
    goto switch_break;
    case_4: /* CIL Label */ 
#line 350
    traversal(root);
    __CrestClearStack(548);
#line 351
    goto switch_break;
    case_5: /* CIL Label */ 
    __CrestLoad(549, (unsigned long )0, (long long )0);
#line 353
    exit(0);
    __CrestClearStack(550);
    switch_default: /* CIL Label */ 
#line 356
    goto switch_break;
    switch_break: /* CIL Label */ ;
    }
  }
  while_break: /* CIL Label */ 
  __CrestLoad(551, (unsigned long )(& __retres5), (long long )__retres5);
  __CrestReturn(552);
#line 315
  return (__retres5);
}
}
void __globinit_b_tree(void) 
{ 


  {
  __CrestInit();
}
}
